apiVersion: apps/v1
kind: Deployment
metadata:
  name: ricky-api
spec:
  selector:
    matchLabels:
      app: ricky-api
  template:
    metadata:
      labels:
        app: ricky-api
    spec:
      containers:
      - name: ricky-api
        image: us-docker.pkg.dev/cit-262-team1-ez/ricky-api/api-tests
        resources:
          limits:
            memory: "500Mi"
            cpu: ".5"
          requests:
            memory: "250Mi"
            cpu: ".25"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          failureThreshold: 1
          periodSeconds: 10
          timeoutSeconds: 10
        startupProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          failureThreshold: 30
          periodSeconds: 10
          timeoutSeconds: 10
        ports:
        - containerPort: 3000